# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JobFinder' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JobFinder

  pod 'Alamofire', '~> 5.0.0.beta.1'
  pod 'SDWebImage', '~>3.8'
  pod 'SelectionList'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  
  target 'JobFinderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JobFinderUITests' do
    inherit! :search_paths
    # Pods for testing
  end







end
